import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <section>
      <Head>
        <title>Crud</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="textxl md:text-5xl text-center font-bold">
          Employee Management
        </h1>
      </main>
    </section>
  );
};

export default Home;
